'use strict';(function(){var keystrokes=[CKEDITOR.CTRL+90,CKEDITOR.CTRL+89,CKEDITOR.CTRL+CKEDITOR.SHIFT+90],backspaceOrDelete={8:1,46:1};CKEDITOR.plugins.add('undo',{lang:'af,ar,bg,bn,bs,ca,cs,cy,da,de,el,en,en-au,en-ca,en-gb,eo,es,et,eu,fa,fi,fo,fr,fr-ca,gl,gu,he,hi,hr,hu,id,is,it,ja,ka,km,ko,ku,lt,lv,mk,mn,ms,nb,nl,no,pl,pt,pt-br,ro,ru,si,sk,sl,sq,sr,sr-latn,sv,th,tr,tt,ug,uk,vi,zh,zh-cn',icons:'redo,redo-rtl,undo,undo-rtl',hidpi:true,init:function(editor){var undoManager=editor.undoManager=new UndoManager(editor),editingHandler=undoManager.editingHandler=new NativeEditingHandler(undoManager);var undoCommand=editor.addCommand('undo',{exec:function(){if(undoManager.undo()){editor.selectionChange();this.fire('afterUndo');}},startDisabled:true,canUndo:false});var redoCommand=editor.addCommand('redo',{exec:function(){if(undoManager.redo()){editor.selectionChange();this.fire('afterRedo');}},startDisabled:true,canUndo:false});editor.setKeystroke([[keystrokes[0],'undo'],[keystrokes[1],'redo'],[keystrokes[2],'redo']]);undoManager.onChange=function(){undoCommand.setState(undoManager.undoable()?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED);redoCommand.setState(undoManager.redoable()?CKEDITOR.TRISTATE_OFF:CKEDITOR.TRISTATE_DISABLED);};function recordCommand(event){if(undoManager.enabled&&event.data.command.canUndo!==false)
undoManager.save();}
editor.on('beforeCommandExec',recordCommand);editor.on('afterCommandExec',recordCommand);editor.on('saveSnapshot',function(evt){undoManager.save(evt.data&&evt.data.contentOnly);});editor.on('contentDom',editingHandler.attachListeners,editingHandler);editor.on('instanceReady',function(){editor.fire('saveSnapshot');});editor.on('beforeModeUnload',function(){editor.mode=='wysiwyg'&&undoManager.save(true);});function toggleUndoManager(){undoManager.enabled=editor.readOnly?false:editor.mode=='wysiwyg';undoManager.onChange();}
editor.on('mode',toggleUndoManager);editor.on('readOnly',toggleUndoManager);if(editor.ui.addButton){editor.ui.addButton('Undo',{label:editor.lang.undo.undo,command:'undo',toolbar:'undo,10'});editor.ui.addButton('Redo',{label:editor.lang.undo.redo,command:'redo',toolbar:'undo,20'});}
editor.resetUndo=function(){undoManager.reset();editor.fire('saveSnapshot');};editor.on('updateSnapshot',function(){if(undoManager.currentImage)
undoManager.update();});editor.on('lockSnapshot',function(evt){var data=evt.data;undoManager.lock(data&&data.dontUpdate,data&&data.forceUpdate);});editor.on('unlockSnapshot',undoManager.unlock,undoManager);}});CKEDITOR.plugins.undo={};var UndoManager=CKEDITOR.plugins.undo.UndoManager=function(editor){this.editor=editor;this.reset();};UndoManager.prototype={keyGroupsEnum:{PRINTABLE:0,FUNCTIONAL:1},strokesRecorded:[0,0],navigationKeyCodes:{37:1,38:1,39:1,40:1,36:1,35:1,33:1,34:1},previousKeyGroup:-1,type:function(keyCode){var keyGroupsEnum=this.keyGroupsEnum,keyGroup=backspaceOrDelete[keyCode]?keyGroupsEnum.FUNCTIONAL:keyGroupsEnum.PRINTABLE,strokesRecorded=this.strokesRecorded[keyGroup]+1,keyGroupChanged=keyGroup!==this.previousKeyGroup,strokesPerSnapshotExceeded=strokesRecorded>=25,oppositeGroup=keyGroup==keyGroupsEnum.FUNCTIONAL?keyGroupsEnum.PRINTABLE:keyGroupsEnum.FUNCTIONAL;if(!this.typing)
onTypingStart(this);if((keyGroupChanged&&this.previousKeyGroup!==-1)||strokesPerSnapshotExceeded){if(keyGroupChanged){this.strokesRecorded[oppositeGroup]=0;if(!this.save(false,this.editingHandler.lastKeydownImage,false))
this.snapshots.splice(this.index+1,this.snapshots.length-this.index-1);}else{strokesRecorded=0;this.editor.fire('saveSnapshot');this.typing=true;}}
this.strokesRecorded[keyGroup]=strokesRecorded;this.previousKeyGroup=keyGroup;this.editor.fire('change');},reset:function(){this.snapshots=[];this.index=-1;this.limit=this.editor.config.undoStackSize||20;this.currentImage=null;this.hasUndo=false;this.hasRedo=false;this.locked=null;this.resetType();},resetType:function(){this.strokesRecorded=[0,0];this.typing=false;this.previousKeyGroup=-1;},refreshState:function(){this.hasUndo=!!this.getNextImage(true);this.hasRedo=!!this.getNextImage(false);this.resetType();this.onChange();},save:function(onContentOnly,image,autoFireChange){var editor=this.editor;if(this.locked||editor.status!='ready'||editor.mode!='wysiwyg')
return false;var editable=editor.editable();if(!editable||editable.status!='ready')
return false;var snapshots=this.snapshots;if(!image)
image=new Image(editor);if(image.contents===false)
return false;if(this.currentImage){if(image.equalsContent(this.currentImage)){if(onContentOnly)
return false;if(image.equalsSelection(this.currentImage))
return false;}else if(autoFireChange!==false)
editor.fire('change');}
snapshots.splice(this.index+1,snapshots.length-this.index-1);if(snapshots.length==this.limit)
snapshots.shift();this.index=snapshots.push(image)-1;this.currentImage=image;if(autoFireChange!==false)
this.refreshState();return true;},restoreImage:function(image){var editor=this.editor,sel;if(image.bookmarks){editor.focus();sel=editor.getSelection();}
this.locked={level:999};this.editor.loadSnapshot(image.contents);if(image.bookmarks)
sel.selectBookmarks(image.bookmarks);else if(CKEDITOR.env.ie){var $range=this.editor.document.getBody().$.createTextRange();$range.collapse(true);$range.select();}
this.locked=null;this.index=image.index;this.currentImage=this.snapshots[this.index];this.update();this.refreshState();editor.fire('change');},getNextImage:function(isUndo){var snapshots=this.snapshots,currentImage=this.currentImage,image,i;if(currentImage){if(isUndo){for(i=this.index-1;i>=0;i--){image=snapshots[i];if(!currentImage.equalsContent(image)){image.index=i;return image;}}}else{for(i=this.index+1;i<snapshots.length;i++){image=snapshots[i];if(!currentImage.equalsContent(image)){image.index=i;return image;}}}}
return null;},redoable:function(){return this.enabled&&this.hasRedo;},undoable:function(){return this.enabled&&this.hasUndo;},undo:function(){if(this.undoable()){this.save(true);var image=this.getNextImage(true);if(image)
return this.restoreImage(image),true;}
return false;},redo:function(){if(this.redoable()){this.save(true);if(this.redoable()){var image=this.getNextImage(false);if(image)
return this.restoreImage(image),true;}}
return false;},update:function(newImage){if(this.locked)
return;if(!newImage)
newImage=new Image(this.editor);var i=this.index,snapshots=this.snapshots;while(i>0&&this.currentImage.equalsContent(snapshots[i-1]))
i-=1;snapshots.splice(i,this.index-i+1,newImage);this.index=i;this.currentImage=newImage;},updateSelection:function(newSnapshot){if(!this.snapshots.length)
return false;var snapshots=this.snapshots,lastImage=snapshots[snapshots.length-1];if(lastImage.equalsContent(newSnapshot)){if(!lastImage.equalsSelection(newSnapshot)){snapshots[snapshots.length-1]=newSnapshot;this.currentImage=newSnapshot;return true;}}
return false;},lock:function(dontUpdate,forceUpdate){if(!this.locked){if(dontUpdate)
this.locked={level:1};else{var update=null;if(forceUpdate)
update=true;else{var imageBefore=new Image(this.editor,true);if(this.currentImage&&this.currentImage.equalsContent(imageBefore))
update=imageBefore;}
this.locked={update:update,level:1};}}
else
this.locked.level++;},unlock:function(){if(this.locked){if(!--this.locked.level){var update=this.locked.update;this.locked=null;if(update===true)
this.update();else if(update){var newImage=new Image(this.editor,true);if(!update.equalsContent(newImage))
this.update();}}}},isNavigationKey:function(keyCode){return!!this.navigationKeyCodes[keyCode];}};function onTypingStart(undoManager){undoManager.typing=true;undoManager.hasUndo=true;undoManager.hasRedo=false;undoManager.onChange();}
var Image=CKEDITOR.plugins.undo.Image=function(editor,contentsOnly){this.editor=editor;editor.fire('beforeUndoImage');var contents=editor.getSnapshot();if(CKEDITOR.env.ie&&contents)
contents=contents.replace(/\s+data-cke-expando=".*?"/g,'');this.contents=contents;if(!contentsOnly){var selection=contents&&editor.getSelection();this.bookmarks=selection&&selection.createBookmarks2(true);}
editor.fire('afterUndoImage');};var protectedAttrs=/\b(?:href|src|name)="[^"]*?"/gi;Image.prototype={equalsContent:function(otherImage){var thisContents=this.contents,otherContents=otherImage.contents;if(CKEDITOR.env.ie&&(CKEDITOR.env.ie7Compat||CKEDITOR.env.quirks)){thisContents=thisContents.replace(protectedAttrs,'');otherContents=otherContents.replace(protectedAttrs,'');}
if(thisContents!=otherContents)
return false;return true;},equalsSelection:function(otherImage){var bookmarksA=this.bookmarks,bookmarksB=otherImage.bookmarks;if(bookmarksA||bookmarksB){if(!bookmarksA||!bookmarksB||bookmarksA.length!=bookmarksB.length)
return false;for(var i=0;i<bookmarksA.length;i++){var bookmarkA=bookmarksA[i],bookmarkB=bookmarksB[i];if(bookmarkA.startOffset!=bookmarkB.startOffset||bookmarkA.endOffset!=bookmarkB.endOffset||!CKEDITOR.tools.arrayCompare(bookmarkA.start,bookmarkB.start)||!CKEDITOR.tools.arrayCompare(bookmarkA.end,bookmarkB.end))
return false;}}
return true;}};var inputFired=0,ignoreInputEvent=false,ignoreInputEventListener=function(){ignoreInputEvent=true;};var NativeEditingHandler=CKEDITOR.plugins.undo.NativeEditingHandler=function(undoManager){this.undoManager=undoManager;};NativeEditingHandler.prototype={onKeydown:function(evt){if(CKEDITOR.tools.indexOf(keystrokes,evt.data.getKeystroke())>-1){evt.data.preventDefault();return;}
var keyCode=evt.data.getKey(),undoManager=this.undoManager;this.lastKeydownImage=new Image(undoManager.editor);if(undoManager.isNavigationKey(keyCode)){if(undoManager.strokesRecorded[0]||undoManager.strokesRecorded[1]){undoManager.save(false,this.lastKeydownImage);undoManager.resetType();}}},onInput:function(){inputFired+=1;if(ignoreInputEvent){inputFired-=1;ignoreInputEvent=false;}},onKeyup:function(evt){var undoManager=this.undoManager,keyCode=evt.data.getKey(),editor=undoManager.editor,ieFunctionKeysWorkaround=CKEDITOR.env.ie&&keyCode in backspaceOrDelete;if(ieFunctionKeysWorkaround&&this.lastKeydownImage){if(this.lastKeydownImage.equalsContent(new Image(editor,true))){return;}else{inputFired+=1;}}
if(inputFired>0){inputFired-=1;undoManager.type(keyCode);}else if(undoManager.isNavigationKey(keyCode)){this.onNavigationKey(true);}},onNavigationKey:function(skipContentCompare){var undoManager=this.undoManager;if(skipContentCompare||!undoManager.save(true,null,false))
undoManager.updateSelection(new Image(undoManager.editor));undoManager.resetType();},resetCounter:function(){inputFired=0;},attachListeners:function(){var editable=this.undoManager.editor.editable(),that=this;editable.attachListener(editable,'keydown',that.onKeydown,that);editable.attachListener(editable,CKEDITOR.env.ie?'keypress':'input',that.onInput,that);editable.attachListener(editable,'keyup',that.onKeyup,that);editable.attachListener(editable,'paste',ignoreInputEventListener);editable.attachListener(editable,'drop',ignoreInputEventListener);editable.attachListener(editable,'click',function(){that.onNavigationKey();});}};})();